### ISSUE TITLE
[BUG] - Regular expression consider correct SSN as a incorrect ones

### ISSUE THREAD

**Issue by TrueJacobG** [personnummer/java#128]
The following regular expression currently considers these SSNs:
041018-0004
011108-0008
850327+0004
681116+0008
690404-0000
940324-0006
020427-0003
060607-0001

to be invalid.

If I understand Luhn algorithm correctly these SSNs should be considered valid.

Could you help validate if this regex pattern is correct?
`
    static {
        regexPattern = Pattern.compile("^(\\d{2})?(\\d{2})(\\d{2})(\\d{2})([-+]?)?((?!000)\\d{3}|[TRSUWXJKLMN]\\d{2})(\\d?)$");
        interimPatternTest = Pattern.compile(interimTestStr);
    }
`

**Comment by Johannestegner** [comment]
Hi there!

The numbers have a few other rules than just the Luhn algorithm (which is primarily used just to calculate the checksum to make sure the number is not written wrong).
The rule you are encountering with those numbers have to do with the `birth numbers`.

Out of the last 4 digits in the number, the final one is the checksum and the three before is the birth number. They can be anything between 001 and 999, the ones you show above are all 000 (which is invalid). That's why the Regexp have a specific check to make sure its not a 000 number used (fail fast).
