### ISSUE TITLE
Travis fails using OracleJDK

### ISSUE THREAD

**Issue by ullenius** [personnummer/java#13]
Travis build fails using Oracle JDK. Oracle has changed the licence for Oracle JDK.

> The Oracle JDK License has changed for releases starting April 16, 2019.
> The new Oracle Technology Network License Agreement for Oracle Java SE is substantially different from prior Oracle JDK licenses.

I suggest **removing it entirely** in favour of OpenJDK. OpenJDK is the reference implementation of Java, and is licensed under GPL v2 with classpath exception.

**Reference links:**
https://launchpad.net/~webupd8team/+archive/ubuntu/java
https://travis-ci.community/t/java-8-failing-download-failed-oracle-jdk-8-is-not-installed/1894

**Comment by Johannestegner** [comment]
Yes, we had to remove one or more of the Oracle JDK tests due to this.
I'm not entirely sure if we should remove Oracle JDK fully though... If it differs in anyway from the Open JDK, we want to be able to catch the issues before they are reported as bugs.

Although, I do think that they are close enough to each other and that a lot of people have been moving away from oracles implementation lately...

@frozzare, what's your take on this? Should we just say bye to oracle or keep the ones that still work?
I would probably vote "remove". :P

**Comment by ullenius** [comment]
> "The official Reference Implementations for Java SE 8 (JSR 337) are based **solely** upon open-source code available from the JDK 8 Project in the OpenJDK Community."
https://jdk.java.net/java-se-ri/8

As of Java 11 they are supposed to be the same thing. Just different licenses. 

> "Different builds will be provided for each license, but these builds are **functionally identical** aside from some cosmetic and packaging differences, described in detail below."
https://blogs.oracle.com/java-platform-group/oracle-jdk-releases-for-java-11-and-later

Just my 2 cents. You guys decide

**Comment by Johannestegner** [comment]
Ah yes, thank you for the information, I think that it should be safe to move over to OpenJDK only then.
