### ISSUE TITLE
Inconsistent validator behaviour

### ISSUE THREAD

**Issue by ullenius** [personnummer/java#18]
`valid(long)` returns `false` for valid personal numbers starting with 0:

`valid(001224-4919L)` - (long) returns `false`
`valid("001224-4919")` (String) returns `true`

Fixed in #17

Issue candidate for wontfix tag? 🙃

**Comment by Johannestegner** [comment]
Hi there @ullenius, thank you for the contribution!

I have been out sick for a while, so have not had the time to take care of this as of yet.
When it comes to the `valid(long)` method, we are discussing if we should remove it or not in the 3.x release (which will likely be the next release).
I will ping here when we have a decision :)

**Comment by Johannestegner** [comment]
Apologies for the extremely slow update on this issue.  
The v3 meta document can be found here: https://github.com/personnummer/meta
Due to a generally large update to the full source I will close this issue and pr connected to it.

Thank you for the contribution and again, sorry for very slow update!
