### ISSUE TITLE
[FEATURE] - support Organization number

### ISSUE THREAD

**Issue by flyhard** [personnummer/java#68]
**Description**

If I pass in a Organization number it should be parsed OK as well.

**Breaking changes**

I suggest a new Factory for creating the PNR and ONR objects to not create breaking changes.

**Comment by Johannestegner** [comment]
Hi there!

Organization numbers is out of scope for this package. With that said, we do have a Organisationsnummer organization here on [github](https://github.com/organisationsnummer) which does not currently have a Java package.
I have started to work on it, but due to lack of time for open source, I haven't been able to fully complete it.

In the Organisationsnummer API, we _do_ support both org and ssn, due to the fact that "enskilda firmor" makes use of standard ssn's. So in that package, it is for sure _in scope_ :)

I will try to take time to implement the Org nr API for Java during the weekend so that it is up and running (cant promise I will have time to complete it, but will for sure try!).

**Comment by Johannestegner** [comment]
Published a v1 of the Java organisationsnummer package today (no maven central package yet, need to get that set up, which takes a while). Feel free to take it for a spin!

https://github.com/organisationsnummer/java
