### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by kumlien** [personnummer/java#8]
Hi guys,
This might be a bug. Using one of the ssn:s in your tests (701063-2391) and then prepending it with a '9' still returns true. 
This test fails:
`assertFalse(Personnummer.valid("9701063-2391"));`

br Svante

**Comment by Johannestegner** [comment]
Thank you for the report!

---
I would say that it is the following regexp pattern that is the issue:
`"(\\d{2})?(\\d{2})(\\d{2})(\\d{2})([-|+]?)?(\\d{3})(\\d?)"`

Seeing that it allows for `{2}?` digits (optional) I'm guessing that it matches the rest and ignores the first number (and only uses it if it is two numbers rather than one). If it should be seen as illegal it should be `either 0 or two` rather than using the optional test.

Not really sure how we should handle this, what do you think @frozzare, force 0-2 numbers maybe?

**Comment by Johannestegner** [comment]
Setting it to `^(\d{2})?(\d{2})(\d{2})(\d{2})([-|+]?)?(\d{3})(\d?)$` (forcing it to be within the bounds) would probably work (as it would see "9701063-2391" as invalid rather than valid-ish).

**Comment by kumlien** [comment]
Yes, that works!

**Comment by frozzare** [comment]
Sounds good @Johannestegner !

**Comment by kumlien** [comment]
Ok then @frozzare @Johannestegner , if you update regexp and unit test I'll close the ticket :)

**Comment by Johannestegner** [comment]
Sorry for slow fix, had RL issues to take care of and then java errors to fight with, hehee.
PR is up, should auto-close the issue as soon as it is merged :)
